// <auto-generated />
namespace CIS726_Assignment2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSemesterOrderFieldMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSemesterOrderFieldMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201303222003154_AddSemesterOrderFieldMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
